// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.31.1
// source: symptom_analysis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SymptomAnalysisServiceClient is the client API for SymptomAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SymptomAnalysisServiceClient interface {
	// Méthode pour analyser le texte/audio et extraire les symptômes
	Analyze(ctx context.Context, in *SymptomAnalysisRequest, opts ...grpc.CallOption) (*SymptomAnalysisResponse, error)
}

type symptomAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSymptomAnalysisServiceClient(cc grpc.ClientConnInterface) SymptomAnalysisServiceClient {
	return &symptomAnalysisServiceClient{cc}
}

func (c *symptomAnalysisServiceClient) Analyze(ctx context.Context, in *SymptomAnalysisRequest, opts ...grpc.CallOption) (*SymptomAnalysisResponse, error) {
	out := new(SymptomAnalysisResponse)
	err := c.cc.Invoke(ctx, "/proto.SymptomAnalysisService/Analyze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SymptomAnalysisServiceServer is the server API for SymptomAnalysisService service.
// All implementations must embed UnimplementedSymptomAnalysisServiceServer
// for forward compatibility
type SymptomAnalysisServiceServer interface {
	// Méthode pour analyser le texte/audio et extraire les symptômes
	Analyze(context.Context, *SymptomAnalysisRequest) (*SymptomAnalysisResponse, error)
	mustEmbedUnimplementedSymptomAnalysisServiceServer()
}

// UnimplementedSymptomAnalysisServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSymptomAnalysisServiceServer struct {
}

func (UnimplementedSymptomAnalysisServiceServer) Analyze(context.Context, *SymptomAnalysisRequest) (*SymptomAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedSymptomAnalysisServiceServer) mustEmbedUnimplementedSymptomAnalysisServiceServer() {
}

// UnsafeSymptomAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SymptomAnalysisServiceServer will
// result in compilation errors.
type UnsafeSymptomAnalysisServiceServer interface {
	mustEmbedUnimplementedSymptomAnalysisServiceServer()
}

func RegisterSymptomAnalysisServiceServer(s grpc.ServiceRegistrar, srv SymptomAnalysisServiceServer) {
	s.RegisterService(&SymptomAnalysisService_ServiceDesc, srv)
}

func _SymptomAnalysisService_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymptomAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymptomAnalysisServiceServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SymptomAnalysisService/Analyze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymptomAnalysisServiceServer).Analyze(ctx, req.(*SymptomAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SymptomAnalysisService_ServiceDesc is the grpc.ServiceDesc for SymptomAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SymptomAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SymptomAnalysisService",
	HandlerType: (*SymptomAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _SymptomAnalysisService_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "symptom_analysis.proto",
}
