# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import symptom_analysis_pb2 as symptom__analysis__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in symptom_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SymptomAnalysisServiceStub(object):
    """Le service qui analyse le texte des symptômes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/proto.SymptomAnalysisService/Analyze',
                request_serializer=symptom__analysis__pb2.SymptomAnalysisRequest.SerializeToString,
                response_deserializer=symptom__analysis__pb2.SymptomAnalysisResponse.FromString,
                _registered_method=True)


class SymptomAnalysisServiceServicer(object):
    """Le service qui analyse le texte des symptômes
    """

    def Analyze(self, request, context):
        """Méthode pour analyser le texte et extraire les symptômes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SymptomAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=symptom__analysis__pb2.SymptomAnalysisRequest.FromString,
                    response_serializer=symptom__analysis__pb2.SymptomAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SymptomAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.SymptomAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SymptomAnalysisService(object):
    """Le service qui analyse le texte des symptômes
    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SymptomAnalysisService/Analyze',
            symptom__analysis__pb2.SymptomAnalysisRequest.SerializeToString,
            symptom__analysis__pb2.SymptomAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
